#version 460

#ifdef GLSLANGVALIDATOR
    // otherwise glslangValidator complains about #include
    #extension GL_GOOGLE_include_directive : require
    //for OpenGL those will be parsed when shader is loaded
#endif

layout(std430, binding = 0) buffer cbtSSBO
{
    uint heap[];
};

#define HEAP_ALREADY_DEFINED
#include "HighLevel.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() 
{
}